# Generated by Django 5.2.6 on 2025-09-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField()),
                ('batch_size', models.IntegerField()),
                ('learning_rate', models.FloatField()),
            ],
        ),
    ]
