# Generated by Django 5.2.6 on 2025-09-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NNvisual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetwork',
            name='activation_function',
            field=models.CharField(choices=[('relu', 'ReLU'), ('sigmoid', 'Sigmoid'), ('tanh', 'Tanh'), ('linear', 'Linear')], default='tanh', max_length=10),
        ),
    ]
